const students = [
  {
    email: "student1@pu.edu.np",
    password: "",
    name: "Ram Sharma",
    address: "Kathmandu",
    contactNo: "",
    activated: true,
    expired: false,
    yearJoined: 2022,
    dateOfBirth: "2004-01-01",
    symbolNo: "22070550",
    puRegNo: "2022-01-69-6599",
    program: "Computer Engineering",
    syllabus: "Computer Old Syllabus",
    level: "Bachelor",
    semester: 1,
    status: "ACTIVE",
  },
  {
    email: "student2@pu.edu.np",
    password: "",
    name: "Shyam Sharma",
    address: "Kathmandu",
    contactNo: "",
    activated: true,
    expired: false,
    yearJoined: 2022,
    dateOfBirth: "2004-01-01",
    symbolNo: "22070551",
    puRegNo: "2022-01-69-6199",
    program: "Computer Engineering",
    syllabus: "Computer Old Syllabus",
    level: "Bachelor",
    semester: 1,
    status: "ACTIVE",
  },
  {
    email: "student3@pu.edu.np",
    password: "",
    name: "Nikhil Upreti",
    address: "Kathmandu",
    contactNo: "",
    activated: true,
    expired: false,
    yearJoined: 2022,
    dateOfBirth: "2004-01-01",
    symbolNo: "22070851",
    puRegNo: "2022-01-69-6179",
    program: "Software Engineering",
    syllabus: "Software Old Syllabus",
    level: "Bachelor",
    semester: 1,
    status: "ACTIVE",
  },
]

const teachers = [
  {
    email: "teacher1@pu.edu.np",
    password: "",
    name: "Hari Devkota",
    address: "Kathmandu",
    contactNo: "",
    activated: true,
    expired: false,
    roles: ["teacher"],
  },
  {
    email: "teacher2@pu.edu.np",
    password: "",
    name: "Bishnu Sharma",
    address: "Kathmandu",
    contactNo: "",
    activated: true,
    expired: false,
    roles: ["teacher"],
  },
]

const admins = [
  {
    email: "admin1@pu.edu.np",
    password: "",
    name: "Main Admin",
    address: "Kathmandu",
    contactNo: "",
    activated: true,
    expired: false,
    roles: ["admin"],
  },
]

module.exports = { admins, students, teachers }
